### ISSUE TITLE
So what are all the features which were added with this code?

### ISSUE THREAD

**Issue by mrawesomey** [JasonLovesDoggo/RedditVideoMakerBot#34]
Please leave a comment about all the features Thanks

**Comment by StopmotionSimonYT** [comment]
Allowing users to choose a reddit thread instead of being randomized.
 Allowing users to choose a background that is picked instead of the Minecraft one.
 Allowing users to choose between any subreddit.
 Allowing users to change voice.
 Checks if a video has already been created
 Light and Dark modes
 Nsfw post filter

**Comment by JasonLovesDoggo** [comment]
massively improved TTS engine
keeps a list of all of the videos ran along with the credit and time ran for each
not overwriting the post on each run

**Comment by mlvps** [comment]
> massively improved TTS engine
> keeps a list of all of the videos ran along with the credit and time ran for each
> not overwriting the post on each run

how do you change the voice?

**Comment by JasonLovesDoggo** [comment]
> > massively improved TTS engine
> > keeps a list of all of the videos ran along with the credit and time ran for each
> > not overwriting the post on each run
> 
> how do you change the voice?

See #44

**Comment by JasonLovesDoggo** [comment]
optional image transparency

**Comment by JasonLovesDoggo** [comment]
improved TTS requests with redundancies
