### ISSUE TITLE
how to set the amount of videos to make multiple videos

### ISSUE THREAD

**Issue by justexistingnow** [JasonLovesDoggo/RedditVideoMakerBot#61]
I saw the updated code but I am a little confused on where to set the amount exactly, I am sorry I am not that experienced with python

**Comment by AppleManPS3** [comment]
You need to use a code editor such as Visual Studio Code (I use Brackets) to edit the .env file which has the amount of iterations the tool should run for.

Look out for:
# set to an int e.g. 1 or 29 and leave blank for once
TIMES_TO_RUN=""

Don't forget to save the .env file as only ".env" as the ".env.template" is only so the file shows in File Explorer/Finder since (.)dot files are usually hidden.

**Comment by justexistingnow** [comment]
Already have a code editor! I didn't see the times to run in the .env file, Sorry

**Comment by AppleManPS3** [comment]
I too have overlooked a few things when I installed this -- no pressure!

**Comment by justexistingnow** [comment]
I am getting an error whenever I try to run it with multiple videos 

`TypeError: range expected at least 1 argument, got 0`

**Comment by AppleManPS3** [comment]
What value have you got in the field currently?

**Comment by justexistingnow** [comment]
18

**Comment by justexistingnow** [comment]
Tried it, Doesn't work still the same error.
`TypeError: range expected at least 1 argument, got 0`

**Comment by JasonLovesDoggo** [comment]
I'll fix it later today
